### ISSUE TITLE
Cromwell Setup Commands Not Working

### ISSUE THREAD

**Issue by yueyaog** [openwdl/learn-wdl#44]
Thank you for creating the amazing learn WDL tutorial. There are two typos in two cromwell setup commands ([learn-wdl](https://github.com/openwdl/learn-wdl)/[5_reference_material](https://github.com/openwdl/learn-wdl/tree/master/5_reference_material)/2_WDL-dev-env.md). The **broadinstitute** was misspelled into **broadinstutite**. Thus those commands are not working. Please update those commands into: 
`curl -L -o cromwell-50.jar https://github.com/broadinstitute/cromwell/releases/download/50/cromwell-50.jar`
`curl -L -o womtool-50.jar https://github.com/broadinstitute/cromwell/releases/download/50/womtool-50.jar`

**Comment by llangit-broad** [comment]
Thanks for catching that, I updated - thanks much
